owner: roava
repo: rova-uptime-checks

sites:
  - name: Rova Dashboard
    url: https://dashboard.dev.getrova.io
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.com
  - name: Rova Website
    url: https://dev.getrova.com
  - name: Rova ArgoCD DEV
    url: https://argocd.dev.getrova.io
    
 
status-website:
  baseUrl: /rova-uptime-checks
  